import type { PrismaClient } from '@prisma/client';
// Generated by Wrangler on Tue May 21 2024 14:50:00 GMT-0500 (Central Daylight Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`
import type en from '@/lib/i18n/messages/en.json';
import type { IRequest } from 'itty-router';
import type { NextRequest } from 'next/server';

declare type NextApiRequest = NextRequest & IRequest;

declare global {
  // 全局持有 Prisma 避免在开发环境下Prisma 链接未关闭导致的报错
  let prisma: PrismaClient | undefined;

  namespace NodeJS {
    interface ProcessEnv {
      // Add any custom process.env variables here
      // NEXT_PUBLIC_API_URL: string;
      S3_ENDPOINT: string;
      S3_REGION: string;
      S3_BUCKET: string;
      S3_DOMAIN: string;
      S3_ACCOUNT_ID: string;
      S3_ACCESS_KEY: string;
      S3_SECRET_KEY: string;
    }
  }
}
// 让IDE能识别`next-intl`的类型的key
declare type Messages = typeof en;
// Use type safe message keys with `next-intl`
// 必须放在顶层定义
declare interface IntlMessages extends Messages {}
